version: '3'

services:
  redis:
    image: redis:alpine
    container_name: socket-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./redis-volume:/data

  server:
    container_name: socket-node
    build :
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - '3000:3000'
    depends_on:
      - redis


